// <auto-generated />
using System;
using Kindergarten.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kindergarten.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250911054757_BigSeeding")]
    partial class BigSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kindergarten.Domain.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendance");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-aaaaaaaaaaaa"),
                            Date = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-bbbbbbbbbbbb"),
                            Date = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-cccccccccccc"),
                            Date = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("aaaa1111-1111-1111-1111-aaaaaaaaaaaa"),
                            Date = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("bbbb1111-1111-1111-1111-bbbbbbbbbbbb"),
                            Date = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-dddddddddddd"),
                            Date = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-5555-5555-5555-eeeeeeeeeeee"),
                            Date = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("ffffffff-6666-6666-6666-ffffffffffff"),
                            Date = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("aaaa2222-2222-2222-2222-aaaaaaaaaaaa"),
                            Date = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("bbbb2222-2222-2222-2222-bbbbbbbbbbbb"),
                            Date = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("11111111-aaaa-bbbb-cccc-111111111111"),
                            Date = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-cccc-dddd-222222222222"),
                            Date = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-dddd-eeee-333333333333"),
                            Date = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("aaaa3333-3333-3333-3333-aaaaaaaaaaaa"),
                            Date = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("bbbb3333-3333-3333-3333-bbbbbbbbbbbb"),
                            Date = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("44444444-aaaa-bbbb-cccc-111111111111"),
                            Date = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("44444444-aaaa-bbbb-cccc-222222222222"),
                            Date = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("44444444-aaaa-bbbb-cccc-333333333333"),
                            Date = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("aaaa4444-4444-4444-4444-aaaaaaaaaaaa"),
                            Date = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("bbbb4444-4444-4444-4444-bbbbbbbbbbbb"),
                            Date = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("55555555-aaaa-bbbb-cccc-111111111111"),
                            Date = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("55555555-aaaa-bbbb-cccc-222222222222"),
                            Date = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("55555555-aaaa-bbbb-cccc-333333333333"),
                            Date = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("aaaa5555-5555-5555-5555-aaaaaaaaaaaa"),
                            Date = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("bbbb5555-5555-5555-5555-bbbbbbbbbbbb"),
                            Date = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("66666666-aaaa-bbbb-cccc-111111111111"),
                            Date = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("66666666-aaaa-bbbb-cccc-222222222222"),
                            Date = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("66666666-aaaa-bbbb-cccc-333333333333"),
                            Date = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("aaaa6666-6666-6666-6666-aaaaaaaaaaaa"),
                            Date = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("bbbb6666-6666-6666-6666-bbbbbbbbbbbb"),
                            Date = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("77777777-aaaa-bbbb-cccc-111111111111"),
                            Date = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("77777777-aaaa-bbbb-cccc-222222222222"),
                            Date = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("77777777-aaaa-bbbb-cccc-333333333333"),
                            Date = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("aaaa7777-7777-7777-7777-aaaaaaaaaaaa"),
                            Date = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("bbbb7777-7777-7777-7777-bbbbbbbbbbbb"),
                            Date = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("88888888-aaaa-bbbb-cccc-111111111111"),
                            Date = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("88888888-aaaa-bbbb-cccc-222222222222"),
                            Date = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("88888888-aaaa-bbbb-cccc-333333333333"),
                            Date = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("aaaa8888-8888-8888-8888-aaaaaaaaaaaa"),
                            Date = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("bbbb8888-8888-8888-8888-bbbbbbbbbbbb"),
                            Date = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("99999999-aaaa-bbbb-cccc-111111111111"),
                            Date = new DateTime(2024, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("99999999-aaaa-bbbb-cccc-222222222222"),
                            Date = new DateTime(2024, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("99999999-aaaa-bbbb-cccc-333333333333"),
                            Date = new DateTime(2024, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("aaaa9999-9999-9999-9999-aaaaaaaaaaaa"),
                            Date = new DateTime(2024, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("bbbb9999-9999-9999-9999-bbbbbbbbbbbb"),
                            Date = new DateTime(2024, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        });
                });

            modelBuilder.Entity("Kindergarten.Domain.Entities.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classroom");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Capacity = 20,
                            Name = "KG1"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Capacity = 25,
                            Name = "KG2"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Capacity = 30,
                            Name = "KG3"
                        });
                });

            modelBuilder.Entity("Kindergarten.Domain.Entities.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parent");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "١٢٣ شارع الرئيسي، القاهرة، مصر",
                            FullName = "أحمد علي",
                            PhoneNumber = "01012345678"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "٤٥٦ شارع الحديقة، الإسكندرية، مصر",
                            FullName = "منى حسن",
                            PhoneNumber = "01098765432"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Address = "٧٨٩ طريق الحديقة، الجيزة، مصر",
                            FullName = "حسام يوسف",
                            PhoneNumber = "0103334444"
                        });
                });

            modelBuilder.Entity("Kindergarten.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrandpaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParentPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("ParentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Address = "١٢٣ شارع الرئيسي، القاهرة، مصر",
                            ClassroomId = new Guid("77777777-7777-7777-7777-777777777777"),
                            DateOfBirth = new DateTime(2019, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "أحمد",
                            FirstName = "عمر",
                            GrandpaName = "محمد",
                            IsActive = true,
                            ParentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ParentPhone = "01012345678"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Address = "٤٥٦ شارع الحديقة، الإسكندرية، مصر",
                            ClassroomId = new Guid("88888888-8888-8888-8888-888888888888"),
                            DateOfBirth = new DateTime(2020, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "منى",
                            FirstName = "سارة",
                            GrandpaName = "علي",
                            IsActive = true,
                            ParentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ParentPhone = "01098765432"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Address = "٧٨٩ طريق الحديقة، الجيزة، مصر",
                            ClassroomId = new Guid("99999999-9999-9999-9999-999999999999"),
                            DateOfBirth = new DateTime(2019, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "حسام",
                            FirstName = "يوسف",
                            GrandpaName = "كامل",
                            IsActive = true,
                            ParentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ParentPhone = "0103334444"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Address = "١٢٣ شارع الرئيسي، القاهرة، مصر",
                            ClassroomId = new Guid("77777777-7777-7777-7777-777777777777"),
                            DateOfBirth = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "أحمد",
                            FirstName = "ملك",
                            GrandpaName = "كمال",
                            IsActive = true,
                            ParentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ParentPhone = "01012345678"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Address = "٤٥٦ شارع الحديقة، الإسكندرية، مصر",
                            ClassroomId = new Guid("88888888-8888-8888-8888-888888888888"),
                            DateOfBirth = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "منى",
                            FirstName = "علا",
                            GrandpaName = "فوزي",
                            IsActive = true,
                            ParentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ParentPhone = "01098765432"
                        },
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-111111111111"),
                            Address = "٧٨٩ طريق الحديقة، الجيزة، مصر",
                            ClassroomId = new Guid("99999999-9999-9999-9999-999999999999"),
                            DateOfBirth = new DateTime(2020, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "حسام",
                            FirstName = "ليلى",
                            GrandpaName = "يوسف",
                            IsActive = true,
                            ParentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ParentPhone = "0103334444"
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-bbbb-bbbb-222222222222"),
                            Address = "١٢٣ شارع الرئيسي، القاهرة، مصر",
                            ClassroomId = new Guid("77777777-7777-7777-7777-777777777777"),
                            DateOfBirth = new DateTime(2019, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "أحمد",
                            FirstName = "محمود",
                            GrandpaName = "سعيد",
                            IsActive = true,
                            ParentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ParentPhone = "01012345678"
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-cccc-cccc-333333333333"),
                            Address = "٤٥٦ شارع الحديقة، الإسكندرية، مصر",
                            ClassroomId = new Guid("88888888-8888-8888-8888-888888888888"),
                            DateOfBirth = new DateTime(2020, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "منى",
                            FirstName = "نور",
                            GrandpaName = "حسن",
                            IsActive = true,
                            ParentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ParentPhone = "01098765432"
                        },
                        new
                        {
                            Id = new Guid("44444444-dddd-dddd-dddd-444444444444"),
                            Address = "٧٨٩ طريق الحديقة، الجيزة، مصر",
                            ClassroomId = new Guid("99999999-9999-9999-9999-999999999999"),
                            DateOfBirth = new DateTime(2019, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "حسام",
                            FirstName = "زياد",
                            GrandpaName = "يوسف",
                            IsActive = true,
                            ParentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ParentPhone = "0103334444"
                        },
                        new
                        {
                            Id = new Guid("55555555-eeee-eeee-eeee-555555555555"),
                            Address = "١٢٣ شارع الرئيسي، القاهرة، مصر",
                            ClassroomId = new Guid("77777777-7777-7777-7777-777777777777"),
                            DateOfBirth = new DateTime(2020, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "أحمد",
                            FirstName = "جنى",
                            GrandpaName = "علي",
                            IsActive = true,
                            ParentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ParentPhone = "01012345678"
                        },
                        new
                        {
                            Id = new Guid("66666666-aaaa-aaaa-aaaa-666666666666"),
                            Address = "٤٥٦ شارع الحديقة، الإسكندرية، مصر",
                            ClassroomId = new Guid("88888888-8888-8888-8888-888888888888"),
                            DateOfBirth = new DateTime(2021, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "منى",
                            FirstName = "فارس",
                            GrandpaName = "حسن",
                            IsActive = true,
                            ParentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ParentPhone = "01098765432"
                        },
                        new
                        {
                            Id = new Guid("77777777-bbbb-bbbb-bbbb-777777777777"),
                            Address = "٧٨٩ طريق الحديقة، الجيزة، مصر",
                            ClassroomId = new Guid("99999999-9999-9999-9999-999999999999"),
                            DateOfBirth = new DateTime(2019, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "حسام",
                            FirstName = "هنا",
                            GrandpaName = "كامل",
                            IsActive = true,
                            ParentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ParentPhone = "0103334444"
                        },
                        new
                        {
                            Id = new Guid("88888888-cccc-cccc-cccc-888888888888"),
                            Address = "١٢٣ شارع الرئيسي، القاهرة، مصر",
                            ClassroomId = new Guid("77777777-7777-7777-7777-777777777777"),
                            DateOfBirth = new DateTime(2020, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "أحمد",
                            FirstName = "سيف",
                            GrandpaName = "محمد",
                            IsActive = true,
                            ParentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ParentPhone = "01012345678"
                        },
                        new
                        {
                            Id = new Guid("99999999-dddd-dddd-dddd-999999999999"),
                            Address = "٤٥٦ شارع الحديقة، الإسكندرية، مصر",
                            ClassroomId = new Guid("88888888-8888-8888-8888-888888888888"),
                            DateOfBirth = new DateTime(2021, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "منى",
                            FirstName = "ريم",
                            GrandpaName = "علي",
                            IsActive = true,
                            ParentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ParentPhone = "01098765432"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa1-eeee-eeee-eeee-aaaaaaaaaaaa"),
                            Address = "٧٨٩ طريق الحديقة، الجيزة، مصر",
                            ClassroomId = new Guid("99999999-9999-9999-9999-999999999999"),
                            DateOfBirth = new DateTime(2019, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "حسام",
                            FirstName = "طارق",
                            GrandpaName = "كامل",
                            IsActive = true,
                            ParentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ParentPhone = "0103334444"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbb2-aaaa-aaaa-aaaa-bbbbbbbbbbbb"),
                            Address = "١٢٣ شارع الرئيسي، القاهرة، مصر",
                            ClassroomId = new Guid("77777777-7777-7777-7777-777777777777"),
                            DateOfBirth = new DateTime(2020, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "أحمد",
                            FirstName = "سلمى",
                            GrandpaName = "كمال",
                            IsActive = true,
                            ParentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ParentPhone = "01012345678"
                        },
                        new
                        {
                            Id = new Guid("ccccccc3-bbbb-bbbb-bbbb-cccccccccccc"),
                            Address = "٤٥٦ شارع الحديقة، الإسكندرية، مصر",
                            ClassroomId = new Guid("88888888-8888-8888-8888-888888888888"),
                            DateOfBirth = new DateTime(2021, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "منى",
                            FirstName = "ياسمين",
                            GrandpaName = "فوزي",
                            IsActive = true,
                            ParentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ParentPhone = "01098765432"
                        },
                        new
                        {
                            Id = new Guid("ddddddd4-cccc-cccc-cccc-dddddddddddd"),
                            Address = "٧٨٩ طريق الحديقة، الجيزة، مصر",
                            ClassroomId = new Guid("99999999-9999-9999-9999-999999999999"),
                            DateOfBirth = new DateTime(2020, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "حسام",
                            FirstName = "حسن",
                            GrandpaName = "يوسف",
                            IsActive = true,
                            ParentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ParentPhone = "0103334444"
                        },
                        new
                        {
                            Id = new Guid("eeeeeee5-dddd-dddd-dddd-eeeeeeeeeeee"),
                            Address = "١٢٣ شارع الرئيسي، القاهرة، مصر",
                            ClassroomId = new Guid("77777777-7777-7777-7777-777777777777"),
                            DateOfBirth = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "أحمد",
                            FirstName = "مريم",
                            GrandpaName = "سعيد",
                            IsActive = true,
                            ParentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ParentPhone = "01012345678"
                        },
                        new
                        {
                            Id = new Guid("fffffff6-eeee-eeee-eeee-ffffffffffff"),
                            Address = "٤٥٦ شارع الحديقة، الإسكندرية، مصر",
                            ClassroomId = new Guid("88888888-8888-8888-8888-888888888888"),
                            DateOfBirth = new DateTime(2020, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "منى",
                            FirstName = "آدم",
                            GrandpaName = "حسن",
                            IsActive = true,
                            ParentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ParentPhone = "01098765432"
                        });
                });

            modelBuilder.Entity("Kindergarten.Domain.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teacher");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            FullName = "فاطمة إبراهيم",
                            IsActive = true,
                            PhoneNumber = "0105551234",
                            Subject = "رياضيات"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            FullName = "أماني صلاح",
                            IsActive = true,
                            PhoneNumber = "0107779999",
                            Subject = "علوم"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            FullName = "عائشة مصطفى",
                            IsActive = true,
                            PhoneNumber = "0102226666",
                            Subject = "عربي"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            FullName = "سعيد عبد الله",
                            IsActive = true,
                            PhoneNumber = "0108881111",
                            Subject = "لغة إنجليزية"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            FullName = "هالة محمود",
                            IsActive = true,
                            PhoneNumber = "0109992222",
                            Subject = "تربية فنية"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            FullName = "خالد حسن",
                            IsActive = true,
                            PhoneNumber = "0103335555",
                            Subject = "تربية رياضية"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            FullName = "منى يوسف",
                            IsActive = true,
                            PhoneNumber = "0104446666",
                            Subject = "علوم الحاسوب"
                        });
                });

            modelBuilder.Entity("Kindergarten.Domain.Entities.TeacherClassroom", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeacherId", "ClassroomId");

                    b.HasIndex("ClassroomId");

                    b.ToTable("TeacherClassroom");

                    b.HasData(
                        new
                        {
                            TeacherId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ClassroomId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            TeacherId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ClassroomId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            TeacherId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ClassroomId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            TeacherId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ClassroomId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            TeacherId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ClassroomId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            TeacherId = new Guid("66666666-6666-6666-6666-666666666666"),
                            ClassroomId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            TeacherId = new Guid("66666666-6666-6666-6666-666666666666"),
                            ClassroomId = new Guid("99999999-9999-9999-9999-999999999999")
                        });
                });

            modelBuilder.Entity("Kindergarten.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("Kindergarten.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Kindergarten.Domain.Entities.Student", b =>
                {
                    b.HasOne("Kindergarten.Domain.Entities.Classroom", "Classroom")
                        .WithMany("Students")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kindergarten.Domain.Entities.Parent", "Parent")
                        .WithMany("Childrens")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Classroom");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Kindergarten.Domain.Entities.TeacherClassroom", b =>
                {
                    b.HasOne("Kindergarten.Domain.Entities.Classroom", "Classroom")
                        .WithMany("TeacherClassrooms")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kindergarten.Domain.Entities.Teacher", "Teacher")
                        .WithMany("TeacherClassrooms")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Kindergarten.Domain.Entities.Classroom", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("TeacherClassrooms");
                });

            modelBuilder.Entity("Kindergarten.Domain.Entities.Parent", b =>
                {
                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("Kindergarten.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("TeacherClassrooms");
                });
#pragma warning restore 612, 618
        }
    }
}
